/**
 * generate-moc.js
 * Called at end of extract.js to rebuild MOC and index notes.
 * Can also be run standalone: node generate-moc.js
 */

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { computeStats, updateReadme } from './stats.js';

const VAULT_ROOT_DEFAULT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export async function generateMOC(vaultRoot = VAULT_ROOT_DEFAULT, _allEntries = null) {
  console.log('\nGenerating MOC and index notes...');

  const stats = await computeStats(vaultRoot);

  // ── 000 Map of Content ────────────────────────────────────────────────────

  // Discover all Sections/ notes on disk if allEntries not passed
  let sectionFiles = [];
  try {
    sectionFiles = await fs.readdir(path.join(vaultRoot, 'Sections'));
    sectionFiles = sectionFiles.filter((f) => f.endsWith('.md'));
  } catch {}

  const sectionLinks = sectionFiles
    .map((f) => `- [[Sections/${f.replace('.md', '')}]]`)
    .sort()
    .join('\n');

  const mocContent = `---
type: moc
cssclasses: [gma2-moc]
tags: [type/moc]
---

# grandMA2 User Manual Vault

Obsidian knowledge vault generated from the [grandMA2 User Manual](https://help.malighting.com/grandMA2/en/help/).

Generated by [grandma2-manual-extractor](https://github.com/thisis-romar/grandma2-manual-vault) · grandPA2-buddy RAG source.

---

## Quick Access

- [[000 Keyword Index]] — all ~200 CLI keywords
- [[000 Key Index]]     — all console keys and buttons

---

## Sections

${sectionLinks || '*No sections generated yet. Run npm run obsidian.*'}

---

## Stats

| Node type | Count |
|---|---|
| Sections | ${stats.sections} |
| Pages | ${stats.pages} |
| Keywords | ${stats.keywords} |
| Keys | ${stats.keys} |
| Quick Start | ${stats.quickStart} |
| **Total** | **${stats.total}** |
`;

  await fs.writeFile(path.join(vaultRoot, '000 Map of Content.md'), mocContent, 'utf8');
  console.log('  Written: 000 Map of Content.md');

  // ── 000 Keyword Index ─────────────────────────────────────────────────────

  let kwFiles = [];
  try {
    kwFiles = await fs.readdir(path.join(vaultRoot, 'Keywords'));
    kwFiles = kwFiles.filter((f) => f.endsWith('.md'));
  } catch {}

  const kwLinks = kwFiles
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
    .map((f) => `- [[Keywords/${f.replace('.md', '')}]]`)
    .join('\n');

  const kwIndexContent = `---
type: moc
cssclasses: [gma2-keyword-index]
tags: [type/moc]
---

# grandMA2 Keyword Index

All CLI keywords extracted from the grandMA2 User Manual.

Total: **${kwFiles.length}** keywords

---

${kwLinks || '*No keywords generated yet.*'}

Part of [[000 Map of Content]]
`;

  await fs.writeFile(path.join(vaultRoot, '000 Keyword Index.md'), kwIndexContent, 'utf8');
  console.log('  Written: 000 Keyword Index.md');

  // ── 000 Key Index ─────────────────────────────────────────────────────────

  let keyFiles = [];
  try {
    keyFiles = await fs.readdir(path.join(vaultRoot, 'Keys'));
    keyFiles = keyFiles.filter((f) => f.endsWith('.md'));
  } catch {}

  const keyLinks = keyFiles
    .sort()
    .map((f) => `- [[Keys/${f.replace('.md', '')}]]`)
    .join('\n');

  const keyIndexContent = `---
type: moc
cssclasses: [gma2-key-index]
tags: [type/moc]
---

# grandMA2 Console Key Index

All physical console keys and buttons.

Total: **${keyFiles.length}** keys

---

${keyLinks || '*No keys generated yet.*'}

Part of [[000 Map of Content]]
`;

  await fs.writeFile(path.join(vaultRoot, '000 Key Index.md'), keyIndexContent, 'utf8');
  console.log('  Written: 000 Key Index.md');

  // Keep the README stats table in sync too.
  await updateReadme(vaultRoot, stats);
  console.log('  README.md stats table updated.');

  console.log('MOC generation complete.');
}

// Run standalone
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateMOC().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
